/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.klarna.secoma;

import static com.klarna.secoma.LogParser.parse;
import static com.klarna.secoma.LogReader.streamLogs;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;

public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	/**
	 * <pre>
	 * Accepts to arguments:
	 *  {@code args[0]} - mandatory path to working directory
	 * </pre>
	 */

	public static void main(String[] args) {
		Path workDir = Paths.get(args[0]);

		Stream<LogEntry> logs = parse(streamLogs(workDir));

		logs.forEach(log -> System.out.println(log));

	}

}
