/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.klarna.secoma;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	/**
	 * <pre>
	 * Accepts to arguments:
	 *  {@code args[0]} - mandatory path to working directory
	 * </pre>
	 */

	public static void main(String[] args) {
		Path workDir = Paths.get(args[0]);

		LogReader reader = new LogReader();

		List<String> rawLogs = reader.getLogs(workDir);
		LogParser parser = new LogParser();
		List<LogEntry> logs = parser.parse(rawLogs);

		logs.forEach(log -> System.err.println(log));

	}

}
