/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.klarna.secoma;

import org.junit.Test;

import com.klarna.secoma.App;

import static org.junit.Assert.*;

public class AppTest {

}
